-- =============================================================================
-- 1분(또는 스케줄) 단위 작업 결과 저장 — Supabase SQL Editor 에서 실행
-- =============================================================================
-- 용도
--   - auto_sell: 매 분 자동 매도 점검 요약(장외/락 스킵/후보 없음/종목별 결과)
--   - 추후 auto_buy_daily, heartbeat 등 job_type 확장 가능
--
-- 보조 테이블 scheduler_minute_items 는 payload.items 와 중복이지만,
--   ticker·outcome 기준 집계·대시보드용으로 쿼리하기 쉽게 둔 것입니다.
--   items 가 없으면 부모만 넣어도 됩니다.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.scheduler_minute_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_type text NOT NULL,
    kst_at timestamptz NOT NULL,
    ny_et_at timestamptz NOT NULL,
    ny_trading_date date NOT NULL,
    market_hours boolean,
    status text NOT NULL,
    success boolean,
    candidate_count integer,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.scheduler_minute_logs IS '스케줄러 분 단위 실행 요약 (텔레그램과 동일 구조의 JSON payload)';

CREATE INDEX IF NOT EXISTS idx_scheduler_minute_logs_job_kst
    ON public.scheduler_minute_logs (job_type, kst_at DESC);

CREATE INDEX IF NOT EXISTS idx_scheduler_minute_logs_ny_date_job
    ON public.scheduler_minute_logs (ny_trading_date DESC, job_type);

CREATE INDEX IF NOT EXISTS idx_scheduler_minute_logs_status
    ON public.scheduler_minute_logs (status, kst_at DESC);

CREATE INDEX IF NOT EXISTS idx_scheduler_minute_logs_payload_gin
    ON public.scheduler_minute_logs USING gin (payload jsonb_path_ops);


CREATE TABLE IF NOT EXISTS public.scheduler_minute_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id bigint NOT NULL REFERENCES public.scheduler_minute_logs (id) ON DELETE CASCADE,
    ticker text,
    stock_name text,
    outcome text NOT NULL,
    exchange_code text,
    quantity integer,
    limit_price double precision,
    error text,
    api_message text,
    sell_reasons jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.scheduler_minute_items IS '분 단위 실행 중 종목별 이벤트(정규화)';

CREATE INDEX IF NOT EXISTS idx_scheduler_minute_items_run_id
    ON public.scheduler_minute_items (run_id);

CREATE INDEX IF NOT EXISTS idx_scheduler_minute_items_ticker
    ON public.scheduler_minute_items (ticker, outcome, created_at DESC);


-- -----------------------------------------------------------------------------
-- (선택) 향후 확장용 테이블 아이디어 — 이번 마이그레이션에는 생성하지 않음
-- -----------------------------------------------------------------------------
-- trading_orders_log        : KIS 주문 요청/응답 원문 + rt_cd (체결 추적)
-- daily_trading_digest      : 장 마감 후 LLM 입력용 하루 1행 요약
-- model_inference_runs      : run_inference 호출 메타(이미 DB에 결과가 있으면 생략 가능)
