-- =============================================================================
-- 총자산/총수익률 시계열 스냅샷 — Supabase SQL Editor 에서 실행
-- =============================================================================
-- 용도
--   - 프론트 대시보드 "그래프 보기"용 시계열
--   - 미국 정규장(ET) 10:00~16:00 매 정각 1회 저장
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.equity_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_key text NOT NULL UNIQUE,          -- 예: "2026-05-07-1000"
    ts_utc timestamptz NOT NULL,
    ts_ny timestamptz NOT NULL,
    ny_trading_date date NOT NULL,
    stock_value_usd double precision NOT NULL DEFAULT 0,
    cash_usd double precision NOT NULL DEFAULT 0,
    total_assets_usd double precision NOT NULL DEFAULT 0,
    total_cost_usd double precision NOT NULL DEFAULT 0,
    total_pnl_usd double precision NOT NULL DEFAULT 0,
    total_return_pct double precision NOT NULL DEFAULT 0,
    source text NOT NULL DEFAULT 'scheduler',
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.equity_snapshots IS '총자산/총수익률 시계열 스냅샷 (프론트 대시보드 그래프용)';

CREATE INDEX IF NOT EXISTS idx_equity_snapshots_ts_utc
    ON public.equity_snapshots (ts_utc DESC);

CREATE INDEX IF NOT EXISTS idx_equity_snapshots_ny_date
    ON public.equity_snapshots (ny_trading_date DESC);
